site_name: "Embedded Systems Course"
site_url: "https://Austin-Fulbright.github.io/embedded-systems-course/"
theme:
  name: material
  custom_dir: overrides

nav:
  - Home: Course/index.md
  - Module 1:
      - Introduction: Course/Introduction/Untitled.md
  - Module 2:
      - C programming: Course/C-programing/Introduction_C.md
      - Embedded Systems Basics: Course/Embedded_Systems_Basics_1/Embedded_Basics.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
